/**
 * 内置提示词清单（BUILTIN_PROMPTS）聚合
 */

import type { PromptSpec } from "./types";
import {
  CLASSIC_PROMPT,
  UPGRADED_PROMPT,
  ANIMATED_PELICAN_PROMPT,
  CLOCK_PROMPT,
  PENROSE_PROMPT,
  ICE_WATER_PROMPT,
} from "./data-classic";
import {
  FOUR_STROKE_ENGINE_PROMPT,
  MOBIUS_STRIP_PROMPT,
  CART_POLE_PROMPT,
  CYBER_CUBE_PROMPT,
  SYNTHWAVE_DRIVE_PROMPT,
  CYBER_HUD_PROMPT,
  BLACK_HOLE_LENSING_PROMPT,
} from "./data-engineering";
import {
  QUANTUM_DOUBLE_SLIT_PROMPT,
  FERROFLUID_SPIKES_PROMPT,
  JWST_DEPLOYMENT_PROMPT,
  TOKAMAK_PLASMA_PROMPT,
  GAA_NANOSHEET_PROMPT,
  CRISPR_CAS9_PROMPT,
  PULSAR_JET_PROMPT,
} from "./data-frontier-visual";
import { HONGLOU_ANIM_PROMPT, HONGLOU_PROMPT } from "../classics/honglou";
import { SANGUO_ANIM_PROMPT, SANGUO_PROMPT } from "../classics/sanguo";
import { SHUIHU_ANIM_PROMPT, SHUIHU_PROMPT } from "../classics/shuihu";
import { XIYOU_ANIM_PROMPT, XIYOU_PROMPT } from "../classics/xiyou";
import { ALL_FRONTIER_PROMPTS } from "../prompts";

export * from "./data-classic";
export * from "./data-engineering";
export * from "./data-frontier-visual";

export const BUILTIN_PROMPTS: readonly PromptSpec[] = [
  CLASSIC_PROMPT,
  UPGRADED_PROMPT,
  ANIMATED_PELICAN_PROMPT,
  CLOCK_PROMPT,
  PENROSE_PROMPT,
  ICE_WATER_PROMPT,
  FOUR_STROKE_ENGINE_PROMPT,
  MOBIUS_STRIP_PROMPT,
  CART_POLE_PROMPT,
  CYBER_CUBE_PROMPT,
  SYNTHWAVE_DRIVE_PROMPT,
  CYBER_HUD_PROMPT,
  BLACK_HOLE_LENSING_PROMPT,
  QUANTUM_DOUBLE_SLIT_PROMPT,
  FERROFLUID_SPIKES_PROMPT,
  JWST_DEPLOYMENT_PROMPT,
  TOKAMAK_PLASMA_PROMPT,
  GAA_NANOSHEET_PROMPT,
  CRISPR_CAS9_PROMPT,
  PULSAR_JET_PROMPT,
  SHUIHU_PROMPT,
  SHUIHU_ANIM_PROMPT,
  XIYOU_PROMPT,
  XIYOU_ANIM_PROMPT,
  SANGUO_PROMPT,
  SANGUO_ANIM_PROMPT,
  HONGLOU_PROMPT,
  HONGLOU_ANIM_PROMPT,
  ...ALL_FRONTIER_PROMPTS,
];
